# Latent Dirichlet Allocation

In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

## Preprocessing

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
#removing stopwords and most common words may part of a document
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [7]:
dtm = cv.fit_transform(npr['Article'])

In [7]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## LDA

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [12]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

## Showing Stored Words

In [13]:
len(cv.get_feature_names())

54777

In [14]:
import random

In [15]:
for i in range(20):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names()[random_word_id])

shelly
copley
maxnesterak
fueling
warp
physicists
benefited
kfc
fancies
tempo
condensed
ambivalent
lashes
biden
calla
anticipating
ian
pinched
mores
gentrification


In [16]:
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names()[random_word_id])

challengers
jabba
penetrates
sweetie
stumps
childlike
assessments
muhly
brushing
litters


### Showing Top Words Per Topic

In [17]:
len(LDA.components_)

7

In [18]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [22]:
len(LDA.components_[6])

54777

In [23]:
single_topic = LDA.components_[0]

In [24]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [25]:
# Word least representative of this topic
single_topic[18302]

0.14285714309286987

In [26]:
# Word most representative of this topic
single_topic[42993]

6247.245510521086

In [27]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [28]:
top_word_indices = single_topic.argsort()[-10:]

In [29]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

new
percent
government
company
million
care
people
health
said
says


These look like business articles perhaps... Let's confirm by using .transform() on our vectorized articles to attach a label number. But first, let's view all the 10 topics found.

In [30]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']


THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']


THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think',

### Attaching Discovered Topic Labels to Original Articles

In [31]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [32]:
dtm.shape

(11992, 54777)

In [33]:
len(npr)

11992

In [34]:
topic_results = LDA.transform(dtm)

In [37]:
topic_results.shape

(11992, 7)

In [38]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [59]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [62]:
topic_results[0].argmax()

1

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [42]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [43]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0], dtype=int64)

In [44]:
npr['Topic'] = topic_results.argmax(axis=1)

In [45]:
npr.head(10)

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      3
9  Eighteen years ago, on New Year’s Eve, David F...      2

In [65]:
npr.Topic.nunique()
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 25 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-25:]])
    print('\n')

THE TOP 25 WORDS FOR TOPIC #0
['law', 'plan', 'states', 'business', 'pay', 'president', 'state', 'tax', 'insurance', 'trump', 'companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']


THE TOP 25 WORDS FOR TOPIC #1
['russian', 'officials', 'press', 'new', 'country', 'white', 'according', 'attack', 'reported', 'war', 'military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']


THE TOP 25 WORDS FOR TOPIC #2
['long', 'small', 'local', 'said', 'life', 'little', 'know', 'don', 'year', 'make', 'way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']


THE TOP 25 WORDS FOR TOPIC #3
['researchers', 'drug', 'use', 'brain', 'help', 'world', 'research', 'university', 'percent', 'care', 'time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just

In [70]:
#Add topic name 
topic_dic = {0:'Business',1:'International_Reltn',2:'Philoshopy',3:'Medical',4:'Election',5:'Music_Literature',6:'Education'}
npr['Topic_Name'] = npr['Topic'].map(topic_dic)

In [72]:
npr.head(50)

Article  Topic  \
0   In the Washington of 2016, even when the polic...      1   
1     Donald Trump has used Twitter  —   his prefe...      1   
2     Donald Trump is unabashedly praising Russian...      1   
3   Updated at 2:50 p. m. ET, Russian President Vl...      1   
4   From photography, illustration and video, to d...      2   
5   I did not want to join yoga class. I hated tho...      3   
6   With a   who has publicly supported the debunk...      3   
7   I was standing by the airport exit, debating w...      2   
8   If movies were trying to be more realistic, pe...      3   
9   Eighteen years ago, on New Year’s Eve, David F...      2   
10  For years now, some of the best, wildest, most...      5   
11  For years now, some of the best, wildest, most...      5   
12  The Colorado River is like a giant bank accoun...      2   
13  For the last installment of NPR’s holiday reci...      2   
14  Being overweight can raise your blood pressure...      3   
15  Who’s the YouTube star of 2016? Adele singing ...      5   
16  Here’s a quick roundup of some of the   you ma...      2   
17  Ben Johnston doesn’t follow the rules of music...      5   
18  David Bowie, Prince and George Michael are all...      5   
19  In November, the typically straitlaced Office ...      1   
20  This is the time of year when everybody is mak...      5   
21  Terrorist attacks, hurricanes, a divisive U. S...      6   
22  We all experience stress at work, no matter th...      6   
23  When John Fahey recorded The New Possibility i...      5   
24  This year was one of   hacks, exploding smartp...      6   
25  From West Virginia to Wyoming, coal country ov...      4   
26  Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...      1   
27  On the morning of Jan. 1, Los Angeles resident...      1   
28  In September, reproductive endocrinologist Joh...      3   
29  In an effort to take advantage of the intimate...      3   
30  Much has been said about the physical and psyc...      3   
31  Editor’s note: This post includes language tha...      4   
32  The   movement, which has been associated with...      4   
33  On New Year’s Day, Portland restaurant Ava Gen...      2   
34  U. S. Supreme Court Chief Justice John Roberts...      4   
35  When Octavia Spencer first read the script for...      5   
36  If you find yourself at a loss to name even on...      2   
37  By day, Nicola Berlinsky and sisters Lisa Pime...      5   
38  It’s that time of year again, when I atone for...      5   
39  For those of us at NPR, 2016 was   of big news...      5   
40  Though many of us lamented the   saga of this ...      4   
41  With so much attention paid to   women in 2016...      3   
42  As the 115th Congress is sworn in Tuesday, Rep...      4   
43  Democrats may have lost the House and the Sena...      4   
44  There’s more methane gas in the atmosphere tha...      6   
45  A Jewish farming couple from Canada says it ha...      2   
46  As Donald Trump prepares to become president, ...      0   
47  The Islamic State issued a statement on Monday...      1   
48  On a September day in 1940 while much of Europ...      2   
49  Hundreds came out New Year’s Day to ride the t...      2   

             Topic_Name  
0   International_Reltn  
1   International_Reltn  
2   International_Reltn  
3   International_Reltn  
4            Philoshopy  
5               Medical  
6               Medical  
7            Philoshopy  
8               Medical  
9            Philoshopy  
10     Music_Literature  
11     Music_Literature  
12           Philoshopy  
13           Philoshopy  
14              Medical  
15     Music_Literature  
16           Philoshopy  
17     Music_Literature  
18     Music_Literature  
19  International_Reltn  
20     Music_Literature  
21            Education  
22            Education  
23     Music_Literature  
24            Education  
25             Election  
26  International_Reltn  
27  International_Reltn  
28              Medical  
2

In [83]:
print(f'\t\t\t\t\tTopic name : {npr.iloc[17].Topic_Name} \n\n\n\n {npr.iloc[17].Article}\n\n\t\t\t\t\t\tEND!!!!')

					Topic name : Music_Literature 



 Ben Johnston doesn’t follow the rules of music. Sure, he’s got degrees from two colleges and a conservatory. But from an early age, Johnston heard music differently. When he was growing up in Georgia, he questioned the standard scales he was taught in school. ”I played by ear and I invented my own chords,” he says. In Western music, we’re taught that there are set notes in scales, but there is actually an infinite number of pitches in between those notes. They’re called microtones, and those are the notes Johnston likes to work with. ”String Quartet No. 4,” Johnston’s take on ”Amazing Grace,” is probably his   and   work. At his home in Madison, Wis. surrounded by a flock of peacocks and a herd of barn cats, the    composer says the work has its roots in his childhood, in slavery and in his desire to hear what the song might have sounded like if Beethoven had covered it late in his career. It was actually Johnston’s love of the Glenn Miller Orche